language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install flake8
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 --statistics shipyard.py convoy/*.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then flake8 --statistics shipyard.py convoy/*.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then flake8 --statistics cascade/*.py tfm/*.py; fi

